<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRoutinesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('routines', function (Blueprint $table) {
            $table->id();

            $table->foreignId('section_id')->constrained();
            $table->foreignId('team_id')->constrained();

            $table->foreignId('item_id')->constrained();

            $table->integer('sequence');
            $table->string('music_title');
            $table->dateTime('start')->nullable();
            $table->dateTime('end')->nullable();

            $table->timestamps();
        });


        // This is NOT a reference table 
        // however I'm going to insert the data for the 
        // May 2021 comps anyway.
/*
      DB::table('routines')->insert([
            [ 'session_item_id' => 1, 'team_id' => 21, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 1, 'team_id' => 123, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 1, 'team_id' => 104, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 1, 'team_id' => 20, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 2, 'team_id' => 21, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 2, 'team_id' => 105, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 2, 'team_id' => 123, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 2, 'team_id' => 20, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 2, 'team_id' => 104, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 3, 'team_id' => 21, 'sequence' => 1, 'music_title' => 'A Sweet Dose' ],
            [ 'session_item_id' => 3, 'team_id' => 123, 'sequence' => 2, 'music_title' => 'Singing in the Rain' ],
            [ 'session_item_id' => 3, 'team_id' => 20, 'sequence' => 3, 'music_title' => 'The Orphanage' ],
            [ 'session_item_id' => 3, 'team_id' => 104, 'sequence' => 4, 'music_title' => 'I\'ve got no strings' ],
            [ 'session_item_id' => 4, 'team_id' => 130, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 151, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 61, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 72, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 51, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 34, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 4, 'team_id' => 140, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 151, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 130, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 140, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 34, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 51, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 72, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 5, 'team_id' => 61, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 6, 'team_id' => 130, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 6, 'team_id' => 151, 'sequence' => 2, 'music_title' => 'Harry Potter' ],
            [ 'session_item_id' => 6, 'team_id' => 34, 'sequence' => 3, 'music_title' => 'What\'s up Doc? ' ],
            [ 'session_item_id' => 6, 'team_id' => 61, 'sequence' => 4, 'music_title' => 'Enchanted Heroines' ],
            [ 'session_item_id' => 6, 'team_id' => 51, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 6, 'team_id' => 140, 'sequence' => 6, 'music_title' => 'Cats in the Night' ],
            [ 'session_item_id' => 6, 'team_id' => 72, 'sequence' => 7, 'music_title' => 'Home Coming' ],
            [ 'session_item_id' => 7, 'team_id' => 59, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 58, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 63, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 2, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 57, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 142, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 32, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 69, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 7, 'team_id' => 138, 'sequence' => 9, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 59, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 58, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 69, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 63, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 57, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 138, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 32, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 142, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 8, 'team_id' => 2, 'sequence' => 9, 'music_title' => '' ],
            [ 'session_item_id' => 9, 'team_id' => 58, 'sequence' => 1, 'music_title' => 'Singing in the Rain' ],
            [ 'session_item_id' => 9, 'team_id' => 32, 'sequence' => 2, 'music_title' => 'Hey Mickey!' ],
            [ 'session_item_id' => 9, 'team_id' => 2, 'sequence' => 3, 'music_title' => 'Broadway' ],
            [ 'session_item_id' => 9, 'team_id' => 138, 'sequence' => 4, 'music_title' => 'World of pure imagination' ],
            [ 'session_item_id' => 9, 'team_id' => 57, 'sequence' => 5, 'music_title' => 'Entertain You' ],
            [ 'session_item_id' => 9, 'team_id' => 69, 'sequence' => 6, 'music_title' => 'Suess' ],
            [ 'session_item_id' => 9, 'team_id' => 142, 'sequence' => 7, 'music_title' => 'Jingle Bell Rock' ],
            [ 'session_item_id' => 9, 'team_id' => 63, 'sequence' => 8, 'music_title' => 'I dream of Genies' ],
            [ 'session_item_id' => 10, 'team_id' => 144, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 10, 'team_id' => 10, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 10, 'team_id' => 143, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 10, 'team_id' => 81, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 10, 'team_id' => 153, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 10, 'team_id' => 29, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 144, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 81, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 29, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 143, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 10, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 11, 'team_id' => 153, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 12, 'team_id' => 29, 'sequence' => 1, 'music_title' => 'Land of Wonder' ],
            [ 'session_item_id' => 12, 'team_id' => 143, 'sequence' => 2, 'music_title' => 'Annie' ],
            [ 'session_item_id' => 12, 'team_id' => 81, 'sequence' => 3, 'music_title' => 'Entertain You' ],
            [ 'session_item_id' => 12, 'team_id' => 153, 'sequence' => 4, 'music_title' => 'Octopus\'s Garden' ],
            [ 'session_item_id' => 12, 'team_id' => 10, 'sequence' => 5, 'music_title' => 'Jolly Holiday' ],
            [ 'session_item_id' => 13, 'team_id' => 66, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 13, 'team_id' => 43, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 13, 'team_id' => 103, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 13, 'team_id' => 19, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 13, 'team_id' => 122, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 14, 'team_id' => 103, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 14, 'team_id' => 66, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 14, 'team_id' => 19, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 14, 'team_id' => 122, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 14, 'team_id' => 43, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 15, 'team_id' => 66, 'sequence' => 1, 'music_title' => 'Winter Wonderland' ],
            [ 'session_item_id' => 15, 'team_id' => 122, 'sequence' => 2, 'music_title' => 'Pinocchio' ],
            [ 'session_item_id' => 15, 'team_id' => 103, 'sequence' => 3, 'music_title' => 'Oliver!' ],
            [ 'session_item_id' => 15, 'team_id' => 19, 'sequence' => 4, 'music_title' => 'Bless our Show' ],
            [ 'session_item_id' => 15, 'team_id' => 43, 'sequence' => 5, 'music_title' => 'Cruella de Vill' ],
            [ 'session_item_id' => 16, 'team_id' => 147, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 136, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 146, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 55, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 150, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 40, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 16, 'team_id' => 12, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 147, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 146, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 12, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 136, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 150, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 40, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 17, 'team_id' => 55, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 18, 'team_id' => 147, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 18, 'team_id' => 12, 'sequence' => 2, 'music_title' => 'A Rumor in St Petersberg' ],
            [ 'session_item_id' => 18, 'team_id' => 146, 'sequence' => 3, 'music_title' => 'The Music Box' ],
            [ 'session_item_id' => 18, 'team_id' => 40, 'sequence' => 4, 'music_title' => 'Arabian Nights' ],
            [ 'session_item_id' => 18, 'team_id' => 55, 'sequence' => 5, 'music_title' => 'Marionettes' ],
            [ 'session_item_id' => 18, 'team_id' => 150, 'sequence' => 6, 'music_title' => 'Christmas with Attitude' ],
            [ 'session_item_id' => 18, 'team_id' => 136, 'sequence' => 7, 'music_title' => 'The Witches' ],
            [ 'session_item_id' => 19, 'team_id' => 85, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 19, 'team_id' => 84, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 19, 'team_id' => 5, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 19, 'team_id' => 133, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 20, 'team_id' => 85, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 20, 'team_id' => 53, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 20, 'team_id' => 133, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 20, 'team_id' => 84, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 20, 'team_id' => 5, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 21, 'team_id' => 85, 'sequence' => 1, 'music_title' => 'Mary Poppins' ],
            [ 'session_item_id' => 21, 'team_id' => 84, 'sequence' => 2, 'music_title' => '101 Dalmations' ],
            [ 'session_item_id' => 21, 'team_id' => 5, 'sequence' => 3, 'music_title' => 'It\'s a hard knock life' ],
            [ 'session_item_id' => 21, 'team_id' => 133, 'sequence' => 4, 'music_title' => 'Annie' ],
            [ 'session_item_id' => 22, 'team_id' => 4, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 22, 'team_id' => 83, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 22, 'team_id' => 17, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 22, 'team_id' => 52, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 22, 'team_id' => 132, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 23, 'team_id' => 4, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 23, 'team_id' => 17, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 23, 'team_id' => 52, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 23, 'team_id' => 132, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 23, 'team_id' => 83, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 24, 'team_id' => 52, 'sequence' => 1, 'music_title' => 'Mama I\'m a Big Girl Now' ],
            [ 'session_item_id' => 24, 'team_id' => 83, 'sequence' => 2, 'music_title' => 'What a Jolly Jingly Surprise' ],
            [ 'session_item_id' => 24, 'team_id' => 4, 'sequence' => 3, 'music_title' => 'Up on the Stage' ],
            [ 'session_item_id' => 24, 'team_id' => 132, 'sequence' => 4, 'music_title' => 'Matilda' ],
            [ 'session_item_id' => 24, 'team_id' => 17, 'sequence' => 5, 'music_title' => 'Annie' ],
            [ 'session_item_id' => 25, 'team_id' => 97, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 25, 'team_id' => 73, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 25, 'team_id' => 101, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 25, 'team_id' => 88, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 25, 'team_id' => 27, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 25, 'team_id' => 111, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 28, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 112, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 27, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 88, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 101, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 97, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 111, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 26, 'team_id' => 73, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 27, 'team_id' => 97, 'sequence' => 1, 'music_title' => 'Upon the Hour' ],
            [ 'session_item_id' => 27, 'team_id' => 101, 'sequence' => 2, 'music_title' => 'A Sunburnt Country' ],
            [ 'session_item_id' => 27, 'team_id' => 27, 'sequence' => 3, 'music_title' => 'Empowerment' ],
            [ 'session_item_id' => 27, 'team_id' => 111, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 27, 'team_id' => 88, 'sequence' => 5, 'music_title' => 'Pearl Harbour' ],
            [ 'session_item_id' => 27, 'team_id' => 73, 'sequence' => 6, 'music_title' => 'The Wild Wild West' ],
            [ 'session_item_id' => 28, 'team_id' => 121, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 28, 'team_id' => 98, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 28, 'team_id' => 102, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 28, 'team_id' => 42, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 28, 'team_id' => 65, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 28, 'team_id' => 18, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 121, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 42, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 98, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 18, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 65, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 29, 'team_id' => 102, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 30, 'team_id' => 18, 'sequence' => 1, 'music_title' => 'A day with Mary' ],
            [ 'session_item_id' => 30, 'team_id' => 98, 'sequence' => 2, 'music_title' => 'I\'ve got Rhythm' ],
            [ 'session_item_id' => 30, 'team_id' => 65, 'sequence' => 3, 'music_title' => 'J\'adore Paris' ],
            [ 'session_item_id' => 30, 'team_id' => 42, 'sequence' => 4, 'music_title' => 'Welcome to Paris' ],
            [ 'session_item_id' => 30, 'team_id' => 121, 'sequence' => 5, 'music_title' => 'Pinocchio' ],
            [ 'session_item_id' => 30, 'team_id' => 102, 'sequence' => 6, 'music_title' => 'The Sweets Shop' ],
            [ 'session_item_id' => 31, 'team_id' => 6, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 31, 'team_id' => 148, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 31, 'team_id' => 62, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 31, 'team_id' => 31, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 31, 'team_id' => 37, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 32, 'team_id' => 62, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 32, 'team_id' => 6, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 32, 'team_id' => 37, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 32, 'team_id' => 31, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 32, 'team_id' => 148, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 33, 'team_id' => 37, 'sequence' => 1, 'music_title' => 'Is that alright?' ],
            [ 'session_item_id' => 33, 'team_id' => 62, 'sequence' => 2, 'music_title' => 'My love for the stage' ],
            [ 'session_item_id' => 33, 'team_id' => 148, 'sequence' => 3, 'music_title' => 'You\'re Never Alone' ],
            [ 'session_item_id' => 33, 'team_id' => 31, 'sequence' => 4, 'music_title' => 'Letters' ],
            [ 'session_item_id' => 33, 'team_id' => 6, 'sequence' => 5, 'music_title' => 'Prince of Egypt' ],
            [ 'session_item_id' => 34, 'team_id' => 94, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 34, 'team_id' => 129, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 34, 'team_id' => 79, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 35, 'team_id' => 94, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 35, 'team_id' => 79, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 35, 'team_id' => 129, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 36, 'team_id' => 94, 'sequence' => 1, 'music_title' => 'A World we Design' ],
            [ 'session_item_id' => 36, 'team_id' => 129, 'sequence' => 2, 'music_title' => 'Find your Voice' ],
            [ 'session_item_id' => 36, 'team_id' => 79, 'sequence' => 3, 'music_title' => 'Arabian Nights' ],
            [ 'session_item_id' => 37, 'team_id' => 78, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 37, 'team_id' => 128, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 37, 'team_id' => 118, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 37, 'team_id' => 93, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 37, 'team_id' => 8, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 37, 'team_id' => 87, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 118, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 128, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 87, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 78, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 8, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 38, 'team_id' => 93, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 39, 'team_id' => 128, 'sequence' => 1, 'music_title' => 'You will be found' ],
            [ 'session_item_id' => 39, 'team_id' => 8, 'sequence' => 2, 'music_title' => 'Pandora\'s Box' ],
            [ 'session_item_id' => 39, 'team_id' => 87, 'sequence' => 3, 'music_title' => 'Pan' ],
            [ 'session_item_id' => 39, 'team_id' => 93, 'sequence' => 4, 'music_title' => 'The Bells of Notre Dame' ],
            [ 'session_item_id' => 39, 'team_id' => 78, 'sequence' => 5, 'music_title' => 'A Love Story' ],
            [ 'session_item_id' => 39, 'team_id' => 118, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 40, 'team_id' => 96, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 40, 'team_id' => 48, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 40, 'team_id' => 26, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 40, 'team_id' => 110, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 41, 'team_id' => 48, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 41, 'team_id' => 96, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 41, 'team_id' => 26, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 41, 'team_id' => 110, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 42, 'team_id' => 48, 'sequence' => 1, 'music_title' => 'Pure Imagination' ],
            [ 'session_item_id' => 42, 'team_id' => 26, 'sequence' => 2, 'music_title' => 'The Kings New Clothes' ],
            [ 'session_item_id' => 43, 'team_id' => 100, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 43, 'team_id' => 109, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 43, 'team_id' => 25, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 43, 'team_id' => 16, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 43, 'team_id' => 95, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 43, 'team_id' => 47, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 100, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 16, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 109, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 25, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 47, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 44, 'team_id' => 95, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 45, 'team_id' => 109, 'sequence' => 1, 'music_title' => 'Fire and Ice' ],
            [ 'session_item_id' => 45, 'team_id' => 100, 'sequence' => 2, 'music_title' => 'I\'m Here' ],
            [ 'session_item_id' => 45, 'team_id' => 95, 'sequence' => 3, 'music_title' => 'The Witch\'s Spell' ],
            [ 'session_item_id' => 45, 'team_id' => 47, 'sequence' => 4, 'music_title' => 'Welcome to Agrabah' ],
            [ 'session_item_id' => 45, 'team_id' => 16, 'sequence' => 5, 'music_title' => 'Pan' ],
            [ 'session_item_id' => 45, 'team_id' => 25, 'sequence' => 6, 'music_title' => 'Bird set free' ],
            [ 'session_item_id' => 46, 'team_id' => 91, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 46, 'team_id' => 90, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 46, 'team_id' => 68, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 46, 'team_id' => 115, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 47, 'team_id' => 91, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 47, 'team_id' => 90, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 47, 'team_id' => 68, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 47, 'team_id' => 115, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 48, 'team_id' => 91, 'sequence' => 1, 'music_title' => 'Build a Snowman' ],
            [ 'session_item_id' => 48, 'team_id' => 90, 'sequence' => 2, 'music_title' => 'All Mixed Up!' ],
            [ 'session_item_id' => 48, 'team_id' => 115, 'sequence' => 3, 'music_title' => 'Barbie World' ],
            [ 'session_item_id' => 49, 'team_id' => 38, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 49, 'team_id' => 114, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 49, 'team_id' => 14, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 49, 'team_id' => 74, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 49, 'team_id' => 67, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 49, 'team_id' => 89, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 14, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 114, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 67, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 89, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 38, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 50, 'team_id' => 74, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 51, 'team_id' => 89, 'sequence' => 1, 'music_title' => 'When in Hollywood' ],
            [ 'session_item_id' => 51, 'team_id' => 38, 'sequence' => 2, 'music_title' => 'Out of the Toybox' ],
            [ 'session_item_id' => 51, 'team_id' => 114, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 51, 'team_id' => 67, 'sequence' => 4, 'music_title' => 'Isn\'t she cute' ],
            [ 'session_item_id' => 51, 'team_id' => 14, 'sequence' => 5, 'music_title' => 'Sing Away your Blues' ],
            [ 'session_item_id' => 51, 'team_id' => 74, 'sequence' => 6, 'music_title' => 'Chitty Chitty' ],
            [ 'session_item_id' => 52, 'team_id' => 1, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 52, 'team_id' => 64, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 52, 'team_id' => 33, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 52, 'team_id' => 3, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 52, 'team_id' => 149, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 52, 'team_id' => 139, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 1, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 64, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 3, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 139, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 149, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 53, 'team_id' => 33, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 54, 'team_id' => 64, 'sequence' => 1, 'music_title' => 'Meet the Muppets' ],
            [ 'session_item_id' => 54, 'team_id' => 1, 'sequence' => 2, 'music_title' => 'Hairspray!' ],
            [ 'session_item_id' => 54, 'team_id' => 139, 'sequence' => 3, 'music_title' => 'Austin Powers' ],
            [ 'session_item_id' => 54, 'team_id' => 33, 'sequence' => 4, 'music_title' => 'Newsies' ],
            [ 'session_item_id' => 54, 'team_id' => 3, 'sequence' => 5, 'music_title' => 'Matilda' ],
            [ 'session_item_id' => 54, 'team_id' => 149, 'sequence' => 6, 'music_title' => 'Welcome to Wonderland' ],
            [ 'session_item_id' => 55, 'team_id' => 13, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 55, 'team_id' => 9, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 55, 'team_id' => 141, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 55, 'team_id' => 82, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 55, 'team_id' => 137, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 55, 'team_id' => 56, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 82, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 141, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 9, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 13, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 56, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 56, 'team_id' => 137, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 57, 'team_id' => 141, 'sequence' => 1, 'music_title' => '"Never Enough"' ],
            [ 'session_item_id' => 57, 'team_id' => 82, 'sequence' => 2, 'music_title' => 'I want 2 B a Dancer' ],
            [ 'session_item_id' => 57, 'team_id' => 13, 'sequence' => 3, 'music_title' => 'Touch the Gold' ],
            [ 'session_item_id' => 57, 'team_id' => 9, 'sequence' => 4, 'music_title' => 'Clown' ],
            [ 'session_item_id' => 57, 'team_id' => 56, 'sequence' => 5, 'music_title' => 'Clown' ],
            [ 'session_item_id' => 57, 'team_id' => 137, 'sequence' => 6, 'music_title' => 'Yesterday' ],
            [ 'session_item_id' => 58, 'team_id' => 127, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 58, 'team_id' => 24, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 58, 'team_id' => 126, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 58, 'team_id' => 108, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 59, 'team_id' => 24, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 59, 'team_id' => 126, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 59, 'team_id' => 108, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 60, 'team_id' => 126, 'sequence' => 1, 'music_title' => 'Hard knock life' ],
            [ 'session_item_id' => 60, 'team_id' => 24, 'sequence' => 2, 'music_title' => 'Christmas Story' ],
            [ 'session_item_id' => 61, 'team_id' => 131, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 61, 'team_id' => 49, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 61, 'team_id' => 119, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 61, 'team_id' => 41, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 61, 'team_id' => 113, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 61, 'team_id' => 80, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 120, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 50, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 119, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 49, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 131, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 113, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 41, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 62, 'team_id' => 80, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 63, 'team_id' => 113, 'sequence' => 1, 'music_title' => 'Pretty Hurts' ],
            [ 'session_item_id' => 63, 'team_id' => 49, 'sequence' => 2, 'music_title' => 'LOVE' ],
            [ 'session_item_id' => 63, 'team_id' => 131, 'sequence' => 3, 'music_title' => 'Funny Honey' ],
            [ 'session_item_id' => 63, 'team_id' => 41, 'sequence' => 4, 'music_title' => 'Arabian Nights' ],
            [ 'session_item_id' => 63, 'team_id' => 119, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 63, 'team_id' => 80, 'sequence' => 6, 'music_title' => 'Somewhere Only We Know' ],
            [ 'session_item_id' => 64, 'team_id' => 135, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 54, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 75, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 35, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 145, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 7, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 64, 'team_id' => 134, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 135, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 54, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 35, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 134, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 75, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 7, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 65, 'team_id' => 145, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 66, 'team_id' => 135, 'sequence' => 1, 'music_title' => 'Dance' ],
            [ 'session_item_id' => 66, 'team_id' => 7, 'sequence' => 2, 'music_title' => 'Magic Man G' ],
            [ 'session_item_id' => 66, 'team_id' => 54, 'sequence' => 3, 'music_title' => 'Hair Up' ],
            [ 'session_item_id' => 66, 'team_id' => 134, 'sequence' => 4, 'music_title' => 'Let\'s Dance' ],
            [ 'session_item_id' => 66, 'team_id' => 35, 'sequence' => 5, 'music_title' => 'Aladdin' ],
            [ 'session_item_id' => 66, 'team_id' => 145, 'sequence' => 6, 'music_title' => 'Which Bathin Suit?' ],
            [ 'session_item_id' => 66, 'team_id' => 75, 'sequence' => 7, 'music_title' => 'Little Shop of Horror' ],
            [ 'session_item_id' => 67, 'team_id' => 152, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 67, 'team_id' => 60, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 67, 'team_id' => 30, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 67, 'team_id' => 36, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 67, 'team_id' => 11, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 68, 'team_id' => 152, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 68, 'team_id' => 36, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 68, 'team_id' => 11, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 68, 'team_id' => 30, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 68, 'team_id' => 60, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 69, 'team_id' => 11, 'sequence' => 1, 'music_title' => 'Party In the USA' ],
            [ 'session_item_id' => 69, 'team_id' => 152, 'sequence' => 2, 'music_title' => 'We are made to Fly' ],
            [ 'session_item_id' => 69, 'team_id' => 60, 'sequence' => 3, 'music_title' => 'Who\'s Dorothy?' ],
            [ 'session_item_id' => 69, 'team_id' => 30, 'sequence' => 4, 'music_title' => 'Be Amazed' ],
            [ 'session_item_id' => 69, 'team_id' => 36, 'sequence' => 5, 'music_title' => 'Let\'s Dance' ],
            [ 'session_item_id' => 70, 'team_id' => 117, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 71, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 92, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 70, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 15, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 39, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 116, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 70, 'team_id' => 86, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 71, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 117, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 15, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 86, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 39, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 116, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 92, 'sequence' => 7, 'music_title' => '' ],
            [ 'session_item_id' => 71, 'team_id' => 70, 'sequence' => 8, 'music_title' => '' ],
            [ 'session_item_id' => 72, 'team_id' => 117, 'sequence' => 1, 'music_title' => 'Let Me Take you to Rio' ],
            [ 'session_item_id' => 72, 'team_id' => 15, 'sequence' => 2, 'music_title' => 'Prom' ],
            [ 'session_item_id' => 72, 'team_id' => 116, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 72, 'team_id' => 70, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 72, 'team_id' => 92, 'sequence' => 5, 'music_title' => 'The Race' ],
            [ 'session_item_id' => 72, 'team_id' => 39, 'sequence' => 6, 'music_title' => 'Adventures of the Big Bad Wolf' ],
            [ 'session_item_id' => 72, 'team_id' => 86, 'sequence' => 7, 'music_title' => 'Little Horrors' ],
            [ 'session_item_id' => 73, 'team_id' => 46, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 73, 'team_id' => 23, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 73, 'team_id' => 45, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 73, 'team_id' => 77, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 73, 'team_id' => 107, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 73, 'team_id' => 125, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 74, 'team_id' => 23, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 74, 'team_id' => 45, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 74, 'team_id' => 107, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 74, 'team_id' => 125, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 74, 'team_id' => 77, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 75, 'team_id' => 23, 'sequence' => 1, 'music_title' => 'A Royal Affair' ],
            [ 'session_item_id' => 75, 'team_id' => 125, 'sequence' => 2, 'music_title' => 'Hairspray' ],
            [ 'session_item_id' => 75, 'team_id' => 77, 'sequence' => 3, 'music_title' => 'Matilda' ],
            [ 'session_item_id' => 76, 'team_id' => 99, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 76, 'team_id' => 106, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 76, 'team_id' => 44, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 76, 'team_id' => 76, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 76, 'team_id' => 124, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 76, 'team_id' => 22, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 106, 'sequence' => 1, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 76, 'sequence' => 2, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 99, 'sequence' => 3, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 44, 'sequence' => 4, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 124, 'sequence' => 5, 'music_title' => '' ],
            [ 'session_item_id' => 77, 'team_id' => 22, 'sequence' => 6, 'music_title' => '' ],
            [ 'session_item_id' => 78, 'team_id' => 76, 'sequence' => 1, 'music_title' => 'Rio' ],
            [ 'session_item_id' => 78, 'team_id' => 106, 'sequence' => 2, 'music_title' => 'The Big Doll House' ],
            [ 'session_item_id' => 78, 'team_id' => 44, 'sequence' => 3, 'music_title' => 'Checkmate' ],
            [ 'session_item_id' => 78, 'team_id' => 99, 'sequence' => 4, 'music_title' => 'Ladies of the 80\'s' ],
            [ 'session_item_id' => 78, 'team_id' => 124, 'sequence' => 5, 'music_title' => 'I love a piano' ],
            [ 'session_item_id' => 78, 'team_id' => 22, 'sequence' => 6, 'music_title' => 'Get served' ],   
        ]);

*/
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('routines');
    }
}
